# First import files

In [83]:
from pandas import *
from datetime import *
from numpy import *
import pandas as pd

## Read csv file and change headers name

In [84]:
a = pd.read_csv(r'Desktop\new1.csv',names=['S.No','POSITION','DOB','FLAG','GENDER','DOJ'],header=0)
a

,S.No,POSITION,DOB,FLAG,GENDER,DOJ
0,1,e4,1/29/1969,S,f,1/14/2009
1,2,Vice President of Engineering,08-01-1971,S,F,1/31/2008
2,3,Engineering Manager,11-12-1974,M,M,11-11-2007
3,4,Senior Tool Designer,12/23/1974,S,M,12-05-2007
4,5,Design Engineer1,9/27/1952,M,F,01-06-2008
5,6,Design Engineer1,03-11-1959,M,M,1/24/2008
6,7,Research and Development Manager,2/24/1987,M,M,02-08-2009
7,8,Research and Development Engineer,06-05-1986,S,F,12/29/2008
8,9,Research and Development Engineer,1/21/1979,M,F,1/16/2009
9,10,Research and Development Manager,11/30/1984,M,M,05-03-2009
10,11,Senior Tool Designer,1/17/1978,S,M,12-05-2010
11,12,Tool Designer,7/29/1959,M,M,12-11-2007
12,13,Tool Designer,5/28/1989,M,F,12/23/2010
13,14,Senior Design Engineer,6/16/1979,S,M,12/30/2010
14,15,Design Engineer1,05-02-1961,M,F,1/18/2011
15,16,Marketing Manager,3/19/1975,S,M,12/20/2007
16,17,Marketing Assistant,05-03-1987,S,M,1/26/2007
17,18,Marketing Specialist,03-06-1978,S,M,02-07-2011
18,19,Marketing Assistant,1/29/1978,S,F,2/14/2011
19,20,Marketing Assistant,3/17/1975,M,F,01-07-2011
20,21,Marketing Specialist,02-04-1986,M,M,03-02-2009
21,22,Marketing Specialist,5/21/1987,S,M,12-12-2008
22,23,Marketing Specialist,9/13/1962,M,F,01-12-2009
23,24,Marketing Specialist,6/18/1979,M,F,1/18/2009
24,25,Vice President of Production,01-07-1983,S,M,02-03-2009
25,26,Production Control Manager,11-03-1982,M,M,12-01-2008
26,27,Production Supervisor - WC60,10-08-1956,S,F,2/27/2008
27,28,Production Technician - WC60,3/13/1988,M,M,6/30/2006
28,29,Production Technician - WC60,9/25/1979,S,M,1/23/2009
29,30,Production Technician - WC60,9/28/1989,M,F,1/29/2009
...,...,...,...,...,...,...
260,261,Purchasing Assistant,1/17/1978,M,M,12/25/2010
261,262,Assistant to the Chief Financial Officer,6/21/1964,S,M,01-12-2009
262,263,Information Services Manager,12/13/1975,S,F,12-11-2008
263,264,Network Manager,3/25/1984,S,F,02-04-2009
264,265,Network Administrator,3/27/1977,S,M,12-04-2008
265,266,Network Administrator,5/28/1980,S,M,2/23/2009
266,267,Application Specialist,5/19/1978,S,F,2/16/2009
267,268,Application Specialist,3/13/1988,S,M,02-03-2009
268,269,Application Specialist,5/26/1987,M,M,01-11-2009
269,270,Database Administrator,5/17/1975,S,M,1/17/2009
270,271,Database Administrator,01-06-1976,M,M,1/22/2009
271,272,Application Specialist,1/30/1985,M,F,12/23/2008
272,273,Vice President of Sales,06-06-1977,S,M,2/15/2011
273,274,North American Sales Manager,10/17/1951,M,M,01-04-2011
274,275,Sales Representative,12/25/1968,S,M,5/31/2011
275,276,Sales Representative,2/27/1980,M,F,5/31/2011
276,277,Sales Representative,8/29/1962,S,F,5/31/2011
277,278,Sales Representative,02-04-1975,M,M,5/31/2011
278,279,Sales Representative,1/18/1974,M,M,5/31/2011
279,280,Sales Representative,12-06-1974,S,F,5/31/2011
280,281,Sales Representative,03-09-1968,M,M,5/31/2011
281,282,Sales Representative,12-11-1963,M,M,5/31/2011
282,283,Sales Representative,02-11-1974,S,M,5/31/2011
283,284,Sales Representative,01-05-1978,M,M,9/30/2012
284,285,Pacific Sales Manager,01-11-1975,M,M,3/14/2013
285,286,Sales Representative,2/14/1977,S,F,5/30/2013
286,287,European Sales Manager,9/20/1957,M,F,4/16/2012
287,288,Sales Representative,07-09-1975,S,F,5/30/2013
288,289,Sales Representative,3/17/1968,M,F,5/30/2012
289,290,Sales Representative,9/30/1975,S,M,5/30/2012

In [87]:
a['NOW'] = datetime.today()  #Use to get today's date and time
a['DOB'] = to_datetime(a['DOB'])  #Create DOB column and arrange its date
b = (a['NOW']-a['DOB'])/timedelta64(1,'Y')  #Use to calculate age
a['Age'] = round(b)  #Use to create Age column and calculate round values 
a['DOJ'] = to_datetime(a['DOJ'])  #Create DOJ column and arrange its date
c = (a['NOW']-a['DOJ'])/timedelta64(1,'Y')  #Use to calculate Experience  
a['Experience'] = round(c)  #Use to create Experience column and calculate round values 
a['Chief'] = a[a['Experience']>=10] ##Use to create Chief column and check its seneority
a
a.drop(['FLAG','GENDER'],axis=1)  #Remove FLAG and GENDER column from table

,S.No,POSITION,DOB,DOJ,NOW,Age,Experience,Chief
0,1,e4,1969-01-29,2009-01-14,2019-06-19 12:05:39.094314,50.0,10.0,1
1,2,Vice President of Engineering,1971-08-01,2008-01-31,2019-06-19 12:05:39.094314,48.0,11.0,2
2,3,Engineering Manager,1974-11-12,2007-11-11,2019-06-19 12:05:39.094314,45.0,12.0,3
3,4,Senior Tool Designer,1974-12-23,2007-12-05,2019-06-19 12:05:39.094314,44.0,12.0,4
4,5,Design Engineer1,1952-09-27,2008-01-06,2019-06-19 12:05:39.094314,67.0,11.0,5
5,6,Design Engineer1,1959-03-11,2008-01-24,2019-06-19 12:05:39.094314,60.0,11.0,6
6,7,Research and Development Manager,1987-02-24,2009-02-08,2019-06-19 12:05:39.094314,32.0,10.0,7
7,8,Research and Development Engineer,1986-06-05,2008-12-29,2019-06-19 12:05:39.094314,33.0,10.0,8
8,9,Research and Development Engineer,1979-01-21,2009-01-16,2019-06-19 12:05:39.094314,40.0,10.0,9
9,10,Research and Development Manager,1984-11-30,2009-05-03,2019-06-19 12:05:39.094314,35.0,10.0,10
10,11,Senior Tool Designer,1978-01-17,2010-12-05,2019-06-19 12:05:39.094314,41.0,9.0,NaN
11,12,Tool Designer,1959-07-29,2007-12-11,2019-06-19 12:05:39.094314,60.0,12.0,12
12,13,Tool Designer,1989-05-28,2010-12-23,2019-06-19 12:05:39.094314,30.0,8.0,NaN
13,14,Senior Design Engineer,1979-06-16,2010-12-30,2019-06-19 12:05:39.094314,40.0,8.0,NaN
14,15,Design Engineer1,1961-05-02,2011-01-18,2019-06-19 12:05:39.094314,58.0,8.0,NaN
15,16,Marketing Manager,1975-03-19,2007-12-20,2019-06-19 12:05:39.094314,44.0,11.0,16
16,17,Marketing Assistant,1987-05-03,2007-01-26,2019-06-19 12:05:39.094314,32.0,12.0,17
17,18,Marketing Specialist,1978-03-06,2011-02-07,2019-06-19 12:05:39.094314,41.0,8.0,NaN
18,19,Marketing Assistant,1978-01-29,2011-02-14,2019-06-19 12:05:39.094314,41.0,8.0,NaN
19,20,Marketing Assistant,1975-03-17,2011-01-07,2019-06-19 12:05:39.094314,44.0,8.0,NaN
20,21,Marketing Specialist,1986-02-04,2009-03-02,2019-06-19 12:05:39.094314,33.0,10.0,21
21,22,Marketing Specialist,1987-05-21,2008-12-12,2019-06-19 12:05:39.094314,32.0,11.0,22
22,23,Marketing Specialist,1962-09-13,2009-01-12,2019-06-19 12:05:39.094314,57.0,10.0,23
23,24,Marketing Specialist,1979-06-18,2009-01-18,2019-06-19 12:05:39.094314,40.0,10.0,24
24,25,Vice President of Production,1983-01-07,2009-02-03,2019-06-19 12:05:39.094314,36.0,10.0,25
25,26,Production Control Manager,1982-11-03,2008-12-01,2019-06-19 12:05:39.094314,37.0,11.0,26
26,27,Production Supervisor - WC60,1956-10-08,2008-02-27,2019-06-19 12:05:39.094314,63.0,11.0,27
27,28,Production Technician - WC60,1988-03-13,2006-06-30,2019-06-19 12:05:39.094314,31.0,13.0,28
28,29,Production Technician - WC60,1979-09-25,2009-01-23,2019-06-19 12:05:39.094314,40.0,10.0,29
29,30,Production Technician - WC60,1989-09-28,2009-01-29,2019-06-19 12:05:39.094314,30.0,10.0,30
...,...,...,...,...,...,...,...,...
260,261,Purchasing Assistant,1978-01-17,2010-12-25,2019-06-19 12:05:39.094314,41.0,8.0,NaN
261,262,Assistant to the Chief Financial Officer,1964-06-21,2009-01-12,2019-06-19 12:05:39.094314,55.0,10.0,262
262,263,Information Services Manager,1975-12-13,2008-12-11,2019-06-19 12:05:39.094314,44.0,11.0,263
263,264,Network Manager,1984-03-25,2009-02-04,2019-06-19 12:05:39.094314,35.0,10.0,264
264,265,Network Administrator,1977-03-27,2008-12-04,2019-06-19 12:05:39.094314,42.0,11.0,265
265,266,Network Administrator,1980-05-28,2009-02-23,2019-06-19 12:05:39.094314,39.0,10.0,266
266,267,Application Specialist,1978-05-19,2009-02-16,2019-06-19 12:05:39.094314,41.0,10.0,267
267,268,Application Specialist,1988-03-13,2009-02-03,2019-06-19 12:05:39.094314,31.0,10.0,268
268,269,Application Specialist,1987-05-26,2009-01-11,2019-06-19 12:05:39.094314,32.0,10.0,269
269,270,Database Administrator,1975-05-17,2009-01-17,2019-06-19 12:05:39.094314,44.0,10.0,270
270,271,Database Administrator,1976-01-06,2009-01-22,2019-06-19 12:05:39.094314,43.0,10.0,271
271,272,Application Specialist,1985-01-30,2008-12-23,2019-06-19 12:05:39.094314,34.0,10.0,272
272,273,Vice President of Sales,1977-06-06,2011-02-15,2019-06-19 12:05:39.094314,42.0,8.0,NaN
273,274,North American Sales Manager,1951-10-17,2011-01-04,2019-06-19 12:05:39.094314,68.0,8.0,NaN
274,275,Sales Representative,1968-12-25,2011-05-31,2019-06-19 12:05:39.094314,50.0,8.0,NaN
275,276,Sales Representative,1980-02-27,2011-05-31,2019-06-19 12:05:39.094314,39.0,8.0,NaN
276,277,Sales Representative,1962-08-29,2011-05-31,2019-06-19 12:05:39.094314,57.0,8.0,NaN
277,278,Sales Representative,1975-02-04,2011-05-31,2019-06-19 12:05:39.094314,44.0,8.0,NaN
278,279,Sales Representative,1974-01-18,2011-05-31,2019-06-19 12:05:39.094314,45.0,8.0,NaN
279,280,Sales Representative,1974-12-06,2011-05-31,2019-06-19 12:05:39.094314,45.0,8.0,NaN
280,281,Sales Representative,1968-03-09,2011-05-31,2019-06-19 12:05:39.094314,51.0,8.0,NaN
281,282,Sales Representative,1963-12-11,2011-05-31,2019-06-19 12:05:39.094314,56.0,8.0,NaN
282,283,Sales Representative,1974-02-11,2011-05-31,2019-06-19 12:05:39.094314,45.0,8.0,NaN
283,284,Sales Representative,1978-01-05,2012-09-30,2019-06-19 12:05:39.094314,41.0,7.0,NaN
284,285,Pacific Sales Manager,1975-01-11,2013-03-14,2019-06-19 12:05:39.094314,44.0,6.0,NaN
285,286,Sales Representative,1977-02-14,2013-05-30,2019-06-19 12:05:39.094314,42.0,6.0,NaN
286,287,European Sales Manager,1957-09-20,2012-04-16,2019-06-19 12:05:39.094314,62.0,7.0,NaN
287,288,Sales Representative,1975-07-09,2013-05-30,2019-06-19 12:05:39.094314,44.0,6.0,NaN
288,289,Sales Representative,1968-03-17,2012-05-30,2019-06-19 12:05:39.094314,51.0,7.0,NaN
289,290,Sales Representative,1975-09-30,2012-05-30,2019-06-19 12:05:39.094314,44.0,7.0,NaN